-- Appendix skeleton v2. Apply on the VM as supabase_admin.
-- Splits legal_framework into legal_basis (citation) + condition_tested, and
-- reseeds the whole framework in cascade order (1 scope incl. reverse hybrid,
-- 2 definitions, 3 primary rule 12aa, 4 secondary 12ab, 5 dual residence 12ae,
-- 6 imported 12ad, 7 carry-forward 12af), renumbered and with the corrected
-- legal grounding. Idempotent: re-running rebuilds the same 32 rows.

alter table public.atad2_appendix_skeleton add column if not exists legal_basis text;
alter table public.atad2_appendix_skeleton add column if not exists condition_tested text;
alter table public.atad2_appendix_skeleton alter column legal_framework drop not null;

delete from public.atad2_appendix_skeleton;

insert into public.atad2_appendix_skeleton
  (row_id, section_id, section_title, legal_basis, condition_tested, effect, allowed_states, driven_by_question_ids, render_if, sort_order, is_active)
values
  ('1.1','1','Scope and taxpayer status (incl. reverse hybrid, art. 2)','Article 2(1) / Article 3 Wet Vpb 1969','The taxpayer is subject to Dutch corporate income tax, as a resident or as a non-resident with a Dutch permanent establishment',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q1","Q2"]'::jsonb,null,0,true),
  ('1.2','1','Scope and taxpayer status (incl. reverse hybrid, art. 2)','Anti-hybrid regime (Afdeling 2.2a Wet Vpb 1969)','A cross-border element is present',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q3"]'::jsonb,null,1,true),
  ('1.3','1','Scope and taxpayer status (incl. reverse hybrid, art. 2)','Article 12ac lid 2 Wet Vpb 1969','A related party (an interest above 25%, raised to 50% for hybrid-entity cases, aggregated with an acting-together group) or a structured arrangement is involved',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q28"]'::jsonb,null,2,true),
  ('1.4','1','Scope and taxpayer status (incl. reverse hybrid, art. 2)','Article 2 Wet Vpb 1969','A related participant treats the Dutch partnership as transparent while it is regarded as non-transparent in the Netherlands or another state (reverse-hybrid classification conflict)',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q4"]'::jsonb,null,3,true),
  ('1.5','1','Scope and taxpayer status (incl. reverse hybrid, art. 2)','Article 2 lid 11 Wet Vpb 1969','50% or more of the voting rights, capital or profit is held, directly or indirectly, by related entities in a state that regards the partnership as taxable',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q4"]'::jsonb,null,4,true),
  ('1.6','1','Scope and taxpayer status (incl. reverse hybrid, art. 2)','Article 2 lid 12 Wet Vpb 1969','The collective-investment exception applies (a UCITS or AIF holding tradable securities with a diversified portfolio)',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'[]'::jsonb,null,5,true),

  ('2.1','2','Definitions (art. 12ac)','Article 12ac lid 2 Wet Vpb 1969','Associated enterprise / related party: an interest of more than 25% (raised to 50% for hybrid-entity cases), aggregated across an acting-together group',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q28"]'::jsonb,null,6,true),
  ('2.2','2','Definitions (art. 12ac)','Article 12ac Wet Vpb 1969','A structured arrangement is present (the mismatch is priced into the terms, or the arrangement is designed to produce it)',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q28"]'::jsonb,null,7,true),
  ('2.3','2','Definitions (art. 12ac)','Article 12ac Wet Vpb 1969','Dual-inclusion income is present (income included in the tax base of both states that can absorb a mismatch)',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q4d","Q11","Q25"]'::jsonb,null,8,true),

  ('3.1','3','Primary rule: hybrid mismatches (art. 12aa)','Article 12aa(1)(a) Wet Vpb 1969','A hybrid financial instrument or hybrid transfer gives a deduction without a corresponding inclusion','D/NI','["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q30","Q8","Q11"]'::jsonb,null,9,true),
  ('3.2','3','Primary rule: hybrid mismatches (art. 12aa)','Article 12aa(1)(b) Wet Vpb 1969','A payment to a hybrid entity gives a deduction without a corresponding inclusion','D/NI','["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q26","Q27"]'::jsonb,null,10,true),
  ('3.3','3','Primary rule: hybrid mismatches (art. 12aa)','Article 12aa(1)(c) Wet Vpb 1969','A payment to an entity with one or more permanent establishments gives a deduction without inclusion through an allocation conflict','D/NI','["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q12","Q13","Q14"]'::jsonb,null,11,true),
  ('3.4','3','Primary rule: hybrid mismatches (art. 12aa)','Article 12aa(1)(d) jo. Article 15e lid 9 Wet Vpb 1969','A disregarded permanent establishment gives a deduction without inclusion; for such a PE the object exemption is set aside (art. 15e lid 9)','D/NI','["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q14","Q18b"]'::jsonb,null,12,true),
  ('3.5','3','Primary rule: hybrid mismatches (art. 12aa)','Article 12aa(1)(e) jo. lid 3 Wet Vpb 1969','A payment by a hybrid entity (a disregarded payment) gives a deduction without inclusion; denied only to the extent it is not set off against dual-inclusion income (lid 3)','D/NI','["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q26","Q27"]'::jsonb,null,13,true),
  ('3.6','3','Primary rule: hybrid mismatches (art. 12aa)','Article 12aa(1)(f) jo. lid 3 Wet Vpb 1969','A deemed payment between head office and permanent establishment gives a deduction without inclusion; denied only to the extent it is not set off against dual-inclusion income (lid 3)','D/NI','["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q20b","Q21b"]'::jsonb,null,14,true),
  ('3.7','3','Primary rule: hybrid mismatches (art. 12aa)','Article 12aa(1)(g) jo. lid 3 Wet Vpb 1969','The same charge is deducted twice (double deduction); denied only to the extent it is not set off against dual-inclusion income (lid 3), with later-year recapture under art. 12af','DD','["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q19","Q4c","Q4d"]'::jsonb,null,15,true),
  ('3.8','3','Primary rule: hybrid mismatches (art. 12aa)','Article 3 Wet Vpb 1969','The foreign head office of the Dutch permanent establishment is located outside the EU',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q31"]'::jsonb,'{"questionId":"Q2","equals":"Yes"}'::jsonb,16,true),
  ('3.9','3','Primary rule: hybrid mismatches (art. 12aa)','Article 12aa(1)(g) Wet Vpb 1969','The same charge is deducted at the foreign head office and at the Dutch permanent establishment (double deduction)','DD','["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q32"]'::jsonb,'{"questionId":"Q2","equals":"Yes"}'::jsonb,17,true),
  ('3.10','3','Primary rule: hybrid mismatches (art. 12aa)','Article 12aa(1)(f) Wet Vpb 1969','A deemed payment to the Dutch permanent establishment is not included at the head office (deduction without inclusion)','D/NI','["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q33","Q34"]'::jsonb,'{"questionId":"Q2","equals":"Yes"}'::jsonb,18,true),
  ('3.11','3','Primary rule: hybrid mismatches (art. 12aa)','Article 12aa(1)(f) Wet Vpb 1969','A non-EU permanent establishment makes a deemed payment to the Dutch permanent establishment that is deductible abroad','D/NI','["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q35"]'::jsonb,'{"questionId":"Q2","equals":"Yes"}'::jsonb,19,true),

  ('4.1','4','Secondary rule: inclusion (art. 12ab)','Article 12ab(1) jo. (3) Wet Vpb 1969','As the recipient state, the Netherlands includes the income where the payer state does not deny the deduction; this applies only to sub-paragraphs (a), (b), (c), (e) and (f), never (d) or (g)',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'[]'::jsonb,null,20,true),

  ('5.1','5','Dual residence (art. 12ae)','Article 12ae Wet Vpb 1969','The taxpayer is a tax resident of two states (dual residence)',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q29"]'::jsonb,null,21,true),
  ('5.2','5','Dual residence (art. 12ae)','Article 12ae Wet Vpb 1969','The same remunerations, payments, charges or losses are deducted in both states','DD','["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q29"]'::jsonb,null,22,true),
  ('5.3','5','Dual residence (art. 12ae)','Article 12ae Wet Vpb 1969','The double deduction is set off against dual-inclusion income',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'[]'::jsonb,null,23,true),
  ('5.4','5','Dual residence (art. 12ae)','Article 12ae(2) Wet Vpb 1969','Where the other state is an EU Member State, the deduction is denied only if a tax treaty makes the taxpayer a resident of that other Member State',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'[]'::jsonb,null,24,true),

  ('6.1','6','Imported mismatches (art. 12ad)','Article 12ad Wet Vpb 1969','The Dutch payment is made to a related party or under a structured arrangement',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q5","Q28"]'::jsonb,null,25,true),
  ('6.2','6','Imported mismatches (art. 12ad)','Article 12ad Wet Vpb 1969','There is a hybrid mismatch (double deduction or deduction without inclusion) elsewhere in the financing chain',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q9","Q10"]'::jsonb,null,26,true),
  ('6.3','6','Imported mismatches (art. 12ad)','Article 12ad Wet Vpb 1969','The Dutch payment funds that foreign cost, directly or indirectly (including back-to-back arrangements)',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q9","Q10"]'::jsonb,null,27,true),
  ('6.4','6','Imported mismatches (art. 12ad)','Article 12ad(2) Wet Vpb 1969','The mismatch is not neutralised in any other state (the carve-out does not apply)',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'["Q11"]'::jsonb,null,28,true),
  ('6.5','6','Imported mismatches (art. 12ad)','Article 12aa / 12ab Wet Vpb 1969','The mismatch is already neutralised in the Netherlands on the same payment, so the imported-mismatch backstop is not reached',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'[]'::jsonb,null,29,true),

  ('7.1','7','Carry-forward of denied deductions (art. 12af)','Article 12af Wet Vpb 1969','A deduction was denied in an earlier year under art. 12aa(1)(e), (f) or (g), or art. 12ae, or income was included under art. 12ab(1)',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'[]'::jsonb,null,30,true),
  ('7.2','7','Carry-forward of denied deductions (art. 12af)','Article 12af Wet Vpb 1969','Dual-inclusion income arises in a later year than the denial, allowing the earlier deduction to be taken (recapture)',null,'["Not triggered","Triggered","Insufficient information"]'::jsonb,'[]'::jsonb,null,31,true);
