// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdptlfgdiovghufruhsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkcHRsZmdkaW92Z2h1ZnJ1aHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzg5MzIsImV4cCI6MjA2OTgxNDkzMn0.s51FbU-sTV_DSchNjI5paAIz4Yz8KufERHWMih1JEKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});